<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Machine Learning with R</title>
  <meta name="description" content="This book is about using R for machine learning purposes.">
  <meta name="generator" content="bookdown 0.3.9 and GitBook 2.6.7">

  <meta property="og:title" content="Machine Learning with R" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This book is about using R for machine learning purposes." />
  <meta name="github-repo" content="fderyckel/machinelearningwithr" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Machine Learning with R" />
  
  <meta name="twitter:description" content="This book is about using R for machine learning purposes." />
  

<meta name="author" content="François de Ryckel">


<meta name="date" content="2017-04-26">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="intro.html">
<link rel="next" href="trees-and-classification.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><strong><a href="./">Machine Learning with R</a></strong></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Prerequisites</a></li>
<li class="chapter" data-level="2" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>2</b> Introduction</a></li>
<li class="chapter" data-level="3" data-path="logistic-regressions.html"><a href="logistic-regressions.html"><i class="fa fa-check"></i><b>3</b> Logistic Regressions</a><ul>
<li class="chapter" data-level="3.1" data-path="logistic-regressions.html"><a href="logistic-regressions.html#introduction"><i class="fa fa-check"></i><b>3.1</b> Introduction</a></li>
<li class="chapter" data-level="3.2" data-path="logistic-regressions.html"><a href="logistic-regressions.html#the-logistic-equation."><i class="fa fa-check"></i><b>3.2</b> The logistic equation.</a></li>
<li class="chapter" data-level="3.3" data-path="logistic-regressions.html"><a href="logistic-regressions.html#performance-of-logistic-regression-model"><i class="fa fa-check"></i><b>3.3</b> Performance of Logistic Regression Model</a></li>
<li class="chapter" data-level="3.4" data-path="logistic-regressions.html"><a href="logistic-regressions.html#setting-up"><i class="fa fa-check"></i><b>3.4</b> Setting up</a></li>
<li class="chapter" data-level="3.5" data-path="logistic-regressions.html"><a href="logistic-regressions.html#example-1"><i class="fa fa-check"></i><b>3.5</b> Example 1</a></li>
<li class="chapter" data-level="3.6" data-path="logistic-regressions.html"><a href="logistic-regressions.html#example-2"><i class="fa fa-check"></i><b>3.6</b> Example 2</a><ul>
<li class="chapter" data-level="3.6.1" data-path="logistic-regressions.html"><a href="logistic-regressions.html#accounting-for-missing-values"><i class="fa fa-check"></i><b>3.6.1</b> Accounting for missing values</a></li>
<li class="chapter" data-level="3.6.2" data-path="logistic-regressions.html"><a href="logistic-regressions.html#imputting-missing-values"><i class="fa fa-check"></i><b>3.6.2</b> Imputting Missing Values</a></li>
<li class="chapter" data-level="3.6.3" data-path="logistic-regressions.html"><a href="logistic-regressions.html#roc-and-auc"><i class="fa fa-check"></i><b>3.6.3</b> ROC and AUC</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="logistic-regressions.html"><a href="logistic-regressions.html#references"><i class="fa fa-check"></i><b>3.7</b> References</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="trees-and-classification.html"><a href="trees-and-classification.html"><i class="fa fa-check"></i><b>4</b> Trees and Classification</a><ul>
<li class="chapter" data-level="4.1" data-path="trees-and-classification.html"><a href="trees-and-classification.html#introduction-1"><i class="fa fa-check"></i><b>4.1</b> Introduction</a></li>
<li class="chapter" data-level="4.2" data-path="trees-and-classification.html"><a href="trees-and-classification.html#first-example."><i class="fa fa-check"></i><b>4.2</b> First example.</a></li>
<li class="chapter" data-level="4.3" data-path="trees-and-classification.html"><a href="trees-and-classification.html#second-example."><i class="fa fa-check"></i><b>4.3</b> Second Example.</a></li>
<li class="chapter" data-level="4.4" data-path="trees-and-classification.html"><a href="trees-and-classification.html#how-does-a-tree-decide-where-to-split"><i class="fa fa-check"></i><b>4.4</b> How does a tree decide where to split?</a></li>
<li class="chapter" data-level="4.5" data-path="trees-and-classification.html"><a href="trees-and-classification.html#third-example."><i class="fa fa-check"></i><b>4.5</b> Third example.</a></li>
<li class="chapter" data-level="4.6" data-path="trees-and-classification.html"><a href="trees-and-classification.html#references-1"><i class="fa fa-check"></i><b>4.6</b> References</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="principal-component-analysis.html"><a href="principal-component-analysis.html"><i class="fa fa-check"></i><b>5</b> Principal Component Analysis</a><ul>
<li class="chapter" data-level="5.1" data-path="principal-component-analysis.html"><a href="principal-component-analysis.html#pca-on-an-easy-example."><i class="fa fa-check"></i><b>5.1</b> PCA on an easy example.</a></li>
<li class="chapter" data-level="5.2" data-path="principal-component-analysis.html"><a href="principal-component-analysis.html#attempt-of-pca-on-technical-indicators."><i class="fa fa-check"></i><b>5.2</b> Attempt of PCA on technical indicators.</a></li>
<li class="chapter" data-level="5.3" data-path="principal-component-analysis.html"><a href="principal-component-analysis.html#doing-pca-and-pcr-with-the-pls-package"><i class="fa fa-check"></i><b>5.3</b> Doing PCA and PCR with the PLS package</a></li>
<li class="chapter" data-level="5.4" data-path="principal-component-analysis.html"><a href="principal-component-analysis.html#references."><i class="fa fa-check"></i><b>5.4</b> References.</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="case-study-mushrooms-classification.html"><a href="case-study-mushrooms-classification.html"><i class="fa fa-check"></i><b>6</b> Case Study - Mushrooms Classification</a><ul>
<li class="chapter" data-level="6.1" data-path="case-study-mushrooms-classification.html"><a href="case-study-mushrooms-classification.html#import-the-data"><i class="fa fa-check"></i><b>6.1</b> Import the data</a></li>
<li class="chapter" data-level="6.2" data-path="case-study-mushrooms-classification.html"><a href="case-study-mushrooms-classification.html#tidy-the-data"><i class="fa fa-check"></i><b>6.2</b> Tidy the data</a></li>
<li class="chapter" data-level="6.3" data-path="case-study-mushrooms-classification.html"><a href="case-study-mushrooms-classification.html#understand-the-data"><i class="fa fa-check"></i><b>6.3</b> Understand the data</a><ul>
<li class="chapter" data-level="6.3.1" data-path="case-study-mushrooms-classification.html"><a href="case-study-mushrooms-classification.html#a.-transform-the-data"><i class="fa fa-check"></i><b>6.3.1</b> A. Transform the data</a></li>
<li class="chapter" data-level="6.3.2" data-path="case-study-mushrooms-classification.html"><a href="case-study-mushrooms-classification.html#a.-visualize-the-data"><i class="fa fa-check"></i><b>6.3.2</b> A. Visualize the data</a></li>
<li class="chapter" data-level="6.3.3" data-path="case-study-mushrooms-classification.html"><a href="case-study-mushrooms-classification.html#a.-modeling"><i class="fa fa-check"></i><b>6.3.3</b> A. Modeling</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="case-study-mushrooms-classification.html"><a href="case-study-mushrooms-classification.html#communication"><i class="fa fa-check"></i><b>6.4</b> Communication</a></li>
<li class="chapter" data-level="6.5" data-path="case-study-mushrooms-classification.html"><a href="case-study-mushrooms-classification.html#example-one"><i class="fa fa-check"></i><b>6.5</b> Example one</a></li>
<li class="chapter" data-level="6.6" data-path="case-study-mushrooms-classification.html"><a href="case-study-mushrooms-classification.html#example-two"><i class="fa fa-check"></i><b>6.6</b> Example two</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="case-study-predicting-survicalship-on-the-titanic.html"><a href="case-study-predicting-survicalship-on-the-titanic.html"><i class="fa fa-check"></i><b>7</b> Case Study - Predicting Survicalship on the Titanic</a><ul>
<li class="chapter" data-level="7.1" data-path="case-study-predicting-survicalship-on-the-titanic.html"><a href="case-study-predicting-survicalship-on-the-titanic.html#import-the-data."><i class="fa fa-check"></i><b>7.1</b> Import the data.</a></li>
<li class="chapter" data-level="7.2" data-path="case-study-predicting-survicalship-on-the-titanic.html"><a href="case-study-predicting-survicalship-on-the-titanic.html#tidy-the-data-1"><i class="fa fa-check"></i><b>7.2</b> Tidy the data</a></li>
<li class="chapter" data-level="7.3" data-path="case-study-predicting-survicalship-on-the-titanic.html"><a href="case-study-predicting-survicalship-on-the-titanic.html#understand-the-data-1"><i class="fa fa-check"></i><b>7.3</b> Understand the data</a><ul>
<li class="chapter" data-level="7.3.1" data-path="case-study-predicting-survicalship-on-the-titanic.html"><a href="case-study-predicting-survicalship-on-the-titanic.html#a.-transform-the-data-1"><i class="fa fa-check"></i><b>7.3.1</b> A. Transform the data</a></li>
<li class="chapter" data-level="7.3.2" data-path="case-study-predicting-survicalship-on-the-titanic.html"><a href="case-study-predicting-survicalship-on-the-titanic.html#a.-vizualize-with-families."><i class="fa fa-check"></i><b>7.3.2</b> A. Vizualize with families.</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="case-study-predicting-survicalship-on-the-titanic.html"><a href="case-study-predicting-survicalship-on-the-titanic.html#a.-visualize-with-cabins."><i class="fa fa-check"></i><b>7.4</b> A. Visualize with cabins.</a></li>
<li class="chapter" data-level="7.5" data-path="case-study-predicting-survicalship-on-the-titanic.html"><a href="case-study-predicting-survicalship-on-the-titanic.html#b.-transform-dealing-with-missing-data."><i class="fa fa-check"></i><b>7.5</b> B. Transform Dealing with missing data.</a><ul>
<li class="chapter" data-level="7.5.1" data-path="case-study-predicting-survicalship-on-the-titanic.html"><a href="case-study-predicting-survicalship-on-the-titanic.html#overview."><i class="fa fa-check"></i><b>7.5.1</b> Overview.</a></li>
<li class="chapter" data-level="7.5.2" data-path="case-study-predicting-survicalship-on-the-titanic.html"><a href="case-study-predicting-survicalship-on-the-titanic.html#c.-transform-more-feature-engineering-with-the-ages-and-others."><i class="fa fa-check"></i><b>7.5.2</b> C. Transform More feature engineering with the ages and others.</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="case-study-predicting-survicalship-on-the-titanic.html"><a href="case-study-predicting-survicalship-on-the-titanic.html#references.-1"><i class="fa fa-check"></i><b>7.6</b> References.</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="final-words.html"><a href="final-words.html"><i class="fa fa-check"></i><b>8</b> Final Words</a></li>
<li class="chapter" data-level="" data-path="references-2.html"><a href="references-2.html"><i class="fa fa-check"></i>References</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Machine Learning with R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="logistic-regressions" class="section level1">
<h1><span class="header-section-number">Chapter 3</span> Logistic Regressions</h1>
<div id="introduction" class="section level2">
<h2><span class="header-section-number">3.1</span> Introduction</h2>
<p>Logistic Regression is a classification algorithm. It is used to predict a binary outcome (1 / 0, Yes / No, True / False) given a set of independent variables. To represent binary / categorical outcome, we use dummy variables. You can also think of logistic regression as a special case of linear regression when the outcome variable is categorical, where we are using log of odds as dependent variable. In simple words, it predicts the probability of occurrence of an event by fitting data to a logit function.<br />
Logistic Regression is part of a larger class of algorithms known as Generalized Linear Model (glm).<br />
Although most logisitc regression should be called <strong>binomial logistic regression</strong>, since the variable to predict is binary, however, logistic regression can also be used to predict a dependent variable which can assume more than 2 values. In this second case we call the model <strong>multinomial logistic regression</strong>. A typical example for instance, would be classifying films between “Entertaining”, “borderline” or “boring”.</p>
</div>
<div id="the-logistic-equation." class="section level2">
<h2><span class="header-section-number">3.2</span> The logistic equation.</h2>
<p>The general equation of the <strong>logit model</strong></p>
<p><span class="math display">\[\mathbf{Y} = \beta_0 + \beta_1  x_1 + \beta_2 x_2 + ... + \beta_n x_n\]</span> where <strong>Y</strong> is the variable to predict.<br />
<span class="math inline">\(\beta\)</span> is the coefficients of the predictors and the <span class="math inline">\(x_i\)</span> are the predictors (aka independent variables).<br />
In logistic regression, we are only concerned about the probability of outcome dependent variable ( success or failure). We should then rewrite our function<br />
<span class="math display">\[p = e^{(\beta_0 + \beta_1 x_1 + \beta_2 x_2 + ... + \beta_n x_n)}\]</span>.<br />
This however does not garantee to have p between 0 and 1.<br />
Let’s then have <span class="math display">\[p = \frac{e^{(\beta_0 + \beta_1 x_1 + \beta_2 x_2 + ... + \beta_n x_n)}} {e^{(\beta_0 + \beta_1 x_1 + \beta_2 x_2 + ... + \beta_n x_n)} + 1}\]</span><br />
or <span class="math display">\[p = \frac {e^Y} {e^Y + 1}\]</span><br />
where <em>p</em> is the probability of success. With little further manipulations, we have <span class="math display">\[\frac {p} {1-p} = e^Y\]</span> and <span class="math display">\[\log{\frac{p} {1-p}} = Y\]</span><br />
If we remember what was <strong>Y</strong>, we get <span class="math display">\[\log{\dfrac{p} {1-p}} = \beta_0 + \beta_1  x_1 + \beta_2 x_2 + ... + \beta_n x_n\]</span></p>
<p>This is the equation used in Logistic Regression. Here (p/1-p) is the odd ratio. Whenever the log of odd ratio is found to be positive, the probability of success is always more than 50%.</p>
</div>
<div id="performance-of-logistic-regression-model" class="section level2">
<h2><span class="header-section-number">3.3</span> Performance of Logistic Regression Model</h2>
<p>To evaluate the performance of a logistic regression model, we can consider a few metrics.</p>
<ul>
<li><strong>AIC (Akaike Information Criteria)</strong> The analogous metric of adjusted R-squared in logistic regression is AIC. AIC is the measure of fit which penalizes model for the number of model coefficients. Therefore, we always prefer model with minimum AIC value.<br />
</li>
<li><strong>Null Deviance and Residual Deviance</strong> Null Deviance indicates the response predicted by a model with nothing but an intercept. Lower the value, better the model. Residual deviance indicates the response predicted by a model on adding independent variables. Lower the value, better the model.<br />
</li>
<li><strong>Confusion Matrix</strong> It is nothing but a tabular representation of Actual vs Predicted values. This helps us to find the accuracy of the model and avoid overfitting.<br />
</li>
<li>We can calcualate the accuracy of our model by <span class="math display">\[\frac {True Positives + True Negatives}{True Positives + True Negatives + False Positives + False Negatives}\]</span><br />
</li>
<li>From confusion matrix, <strong>Specificity</strong> and <strong>Sensitivity</strong> can be derived as <span class="math display">\[Specificity = \frac {True Negatives} {True Negative + False Positive}\]</span> and <span class="math display">\[Sensitivity = \frac{True Positive}{True Positive + False Negative}\]</span><br />
</li>
<li><strong>ROC Curve</strong> Receiver Operating Characteristic(ROC) summarizes the model’s performance by evaluating the trade offs between true positive rate (sensitivity) and false positive rate(1- specificity). For plotting ROC, it is advisable to assume p &gt; 0.5 since we are more concerned about success rate. ROC summarizes the predictive power for all possible values of p &gt; 0.5. The area under curve (AUC), referred to as index of accuracy(A) or concordance index, is a perfect performance metric for ROC curve. Higher the area under curve, better the prediction power of the model. The ROC of a perfect predictive model has TP equals 1 and FP equals 0. This curve will touch the top left corner of the graph.</li>
</ul>
</div>
<div id="setting-up" class="section level2">
<h2><span class="header-section-number">3.4</span> Setting up</h2>
<p>As usual we will use the <code>tidyverse</code> and <code>caret</code> package</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(caret)      <span class="co"># For confusion matrix</span>
<span class="kw">library</span>(ROCR)       <span class="co"># For the ROC curve</span>
<span class="kw">library</span>(tidyverse)</code></pre></div>
<p>We can now get straight to business and see how to model logisitc regression with R and then have the more interesting discussion on its performance.</p>
</div>
<div id="example-1" class="section level2">
<h2><span class="header-section-number">3.5</span> Example 1</h2>
<p>We use a dataset about factors influencing graduate admission that can be downloaded from the <a href="http://www.ats.ucla.edu/stat/data/binary.csv">UCLA Institute for Digital Research and Education</a></p>
<p>The dataset has 4 variables</p>
<ul>
<li><code>admit</code> is the response variable<br />
</li>
<li><code>gre</code> is the result of a standardized test<br />
</li>
<li><code>gpa</code> is the result of the student GPA (school reported)</li>
<li><code>rank</code> is the type of university the student apply for (4 = Ivy League, 1 = lower level entry U.)</li>
</ul>
<p>Let’s have a quick look at the data and their summary. The goal is to get familiar with the data, type of predictors (continuous, discrete, categorical, etc.)</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">df &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;dataset/grad_admission.csv&quot;</span>)
<span class="kw">glimpse</span>(df)</code></pre></div>
<pre><code>## Observations: 400
## Variables: 4
## $ admit &lt;int&gt; 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,...
## $ gre   &lt;int&gt; 380, 660, 800, 640, 520, 760, 560, 400, 540, 700, 800, 4...
## $ gpa   &lt;dbl&gt; 3.61, 3.67, 4.00, 3.19, 2.93, 3.00, 2.98, 3.08, 3.39, 3....
## $ rank  &lt;int&gt; 3, 3, 1, 4, 4, 2, 1, 2, 3, 2, 4, 1, 1, 2, 1, 3, 4, 3, 2,...</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#Quick check to see if our response variable is balanced-ish</span>
<span class="kw">table</span>(df$admit)</code></pre></div>
<pre><code>## 
##   0   1 
## 273 127</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">## Two-way contingency table of categorical outcome and predictors
<span class="kw">round</span>(<span class="kw">prop.table</span>(<span class="kw">table</span>(df$admit, df$rank), <span class="dv">2</span>), <span class="dv">2</span>)</code></pre></div>
<pre><code>##    
##        1    2    3    4
##   0 0.46 0.64 0.77 0.82
##   1 0.54 0.36 0.23 0.18</code></pre>
<p>It seems about right … most students applying to Ivy Leagues are not being admitted.</p>
<p>Before we can run our model, let’s transform the <code>rank</code> explanatory variable to a factor.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">df$rank &lt;-<span class="st"> </span><span class="kw">factor</span>(df$rank)

<span class="co"># Run the model</span>
model_admission_lr &lt;-<span class="st"> </span><span class="kw">glm</span>(admit ~<span class="st"> </span>., <span class="dt">data =</span> df, <span class="dt">family =</span> <span class="st">&quot;binomial&quot;</span>)
<span class="kw">summary</span>(model_admission_lr)</code></pre></div>
<pre><code>## 
## Call:
## glm(formula = admit ~ ., family = &quot;binomial&quot;, data = df)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.6268  -0.8662  -0.6388   1.1490   2.0790  
## 
## Coefficients:
##              Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -3.989979   1.139951  -3.500 0.000465 ***
## gre          0.002264   0.001094   2.070 0.038465 *  
## gpa          0.804038   0.331819   2.423 0.015388 *  
## rank2       -0.675443   0.316490  -2.134 0.032829 *  
## rank3       -1.340204   0.345306  -3.881 0.000104 ***
## rank4       -1.551464   0.417832  -3.713 0.000205 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 499.98  on 399  degrees of freedom
## Residual deviance: 458.52  on 394  degrees of freedom
## AIC: 470.52
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>The next part of the output shows the coefficients, their standard errors, the z-statistic (sometimes called a Wald z-statistic), and the associated p-values. Both gre and gpa are statistically significant, as are the three terms for rank. The logistic regression coefficients give the change in the log odds of the outcome for a one unit increase in the predictor variable.<br />
For every one unit change in <code>gre</code>, the log odds of admission (versus non-admission) increases by 0.002.<br />
For a one unit increase in <code>gpa</code>, the log odds of being admitted to graduate school increases by 0.804.<br />
The indicator variables for <code>rank</code> have a slightly different interpretation. For example, having attended an undergraduate institution with rank of 2, versus an institution with a rank of 1, changes the log odds of admission by -0.675.</p>
<p>To see how the variables in the model participates in the decrease of <em>Residual Deviance</em>, we can use the <code>ANOVA</code> function on our model.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">anova</span>(model_admission_lr)</code></pre></div>
<pre><code>## Analysis of Deviance Table
## 
## Model: binomial, link: logit
## 
## Response: admit
## 
## Terms added sequentially (first to last)
## 
## 
##      Df Deviance Resid. Df Resid. Dev
## NULL                   399     499.98
## gre   1  13.9204       398     486.06
## gpa   1   5.7122       397     480.34
## rank  3  21.8265       394     458.52</code></pre>
<p>We can test for an overall effect of <code>rank</code> using the <code>wald.test function</code> of the <code>aod</code> library. The order in which the coefficients are given in the table of coefficients is the same as the order of the terms in the model. This is important because the wald.test function refers to the coefficients by their order in the model. We use the wald.test function. <code>b</code> supplies the coefficients, while <code>Sigma</code> supplies the variance covariance matrix of the error terms, finally <code>Terms</code> tells R which terms in the model are to be tested, in this case, terms 4, 5, and 6, are the three terms for the levels of <code>rank</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(aod)
<span class="kw">wald.test</span>(<span class="dt">Sigma =</span> <span class="kw">vcov</span>(model_admission_lr), <span class="dt">b =</span> <span class="kw">coef</span>(model_admission_lr), <span class="dt">Terms =</span> <span class="dv">4</span>:<span class="dv">6</span>)</code></pre></div>
<pre><code>## Wald test:
## ----------
## 
## Chi-squared test:
## X2 = 20.9, df = 3, P(&gt; X2) = 0.00011</code></pre>
<p>The chi-squared test statistic of 20.9, with three degrees of freedom is associated with a p-value of 0.00011 indicating that the overall effect of rank is statistically significant.</p>
<p>Let’s check how our model is performing. As mentioned earlier, we need to make a choice on the cutoff value (returned probability) to check our accuracy. In this first example, let’s just stick with the usual <code>0.5</code> cutoff value.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">prediction_admission_lr &lt;-<span class="st"> </span><span class="kw">predict</span>(model_admission_lr, <span class="dt">data =</span> df, <span class="dt">type =</span> <span class="st">&quot;response&quot;</span>)
prediction_admission_lr &lt;-<span class="st"> </span><span class="kw">if_else</span>(prediction_admission_lr &gt;<span class="st"> </span><span class="fl">0.5</span> , <span class="dv">1</span>, <span class="dv">0</span>)
<span class="kw">confusionMatrix</span>(<span class="dt">data =</span> prediction_admission_lr, 
<span class="dt">reference =</span> df$admit, 
<span class="dt">positive =</span> <span class="st">&quot;1&quot;</span>)</code></pre></div>
<pre><code>## Confusion Matrix and Statistics
## 
##           Reference
## Prediction   0   1
##          0 254  97
##          1  19  30
##                                          
##                Accuracy : 0.71           
##                  95% CI : (0.6628, 0.754)
##     No Information Rate : 0.6825         
##     P-Value [Acc &gt; NIR] : 0.1293         
##                                          
##                   Kappa : 0.1994         
##  Mcnemar&#39;s Test P-Value : 8.724e-13      
##                                          
##             Sensitivity : 0.2362         
##             Specificity : 0.9304         
##          Pos Pred Value : 0.6122         
##          Neg Pred Value : 0.7236         
##              Prevalence : 0.3175         
##          Detection Rate : 0.0750         
##    Detection Prevalence : 0.1225         
##       Balanced Accuracy : 0.5833         
##                                          
##        &#39;Positive&#39; Class : 1              
## </code></pre>
<p>We have an interesting situation here. Although all our variables were significant in our model, the accuracy of our model, <code>71%</code> is just a little bit higher than the basic benchmark which is the no-information model (ie. we just predict the highest class) in this case <code>68.25%</code>.</p>
<p>Before we do a ROC curve, let’s have a quick reminder on ROC.<br />
ROC are plotting the proprotion of TP to FP. So ideally we want to have 100% TP and 0% FP.<br />
<img src="otherpics/perfect_ROC.png" alt="Perfect ROC Curve" /></p>
<p>Pure Random guessing should lead to this curve<br />
<img src="otherpics/random_ROC.png" alt="random guess" /></p>
<p>With that in mind, let’s do a ROC curve on out model</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">prediction_admission_lr &lt;-<span class="st"> </span><span class="kw">predict</span>(model_admission_lr, <span class="dt">data =</span> df, <span class="dt">type=</span><span class="st">&quot;response&quot;</span>)
pr_admission &lt;-<span class="st"> </span><span class="kw">prediction</span>(prediction_admission_lr, df$admit)
prf_admission &lt;-<span class="st"> </span><span class="kw">performance</span>(pr_admission, <span class="dt">measure =</span> <span class="st">&quot;tpr&quot;</span>, <span class="dt">x.measure =</span> <span class="st">&quot;fpr&quot;</span>)
<span class="kw">plot</span>(prf_admission, <span class="dt">colorize =</span> <span class="ot">TRUE</span>, <span class="dt">lwd=</span><span class="dv">3</span>)</code></pre></div>
<p><img src="machinelearningwithR_files/figure-html/roc_admission_pic1-1.png" width="672" /></p>
<p>At least it is better than just random guessing.</p>
<p>In some applications of ROC curves, you want the point closest to the TPR of <span class="math inline">\(1\)</span> and FPR of <span class="math inline">\(0\)</span>. This cut point is “optimal” in the sense it weighs both sensitivity and specificity equally. Now, there is a cost measure in the ROCR package that you can use to create a performance object. Use it to find the cutoff with minimum cost.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">cost_admission_perf =<span class="st"> </span><span class="kw">performance</span>(pr_admission, <span class="st">&quot;cost&quot;</span>)
pr_admission@cutoffs[[<span class="dv">1</span>]][<span class="kw">which.min</span>(cost_admission_perf@y.values[[<span class="dv">1</span>]])]</code></pre></div>
<pre><code>##      392 
## 0.487194</code></pre>
<p>Using that cutoff value we should get our sensitivity and specificity a bit more in balance. Let’s try</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">prediction_admission_lr &lt;-<span class="st"> </span><span class="kw">predict</span>(model_admission_lr, <span class="dt">data =</span> df, <span class="dt">type =</span> <span class="st">&quot;response&quot;</span>)
prediction_admission_lr &lt;-<span class="st"> </span><span class="kw">if_else</span>(prediction_admission_lr &gt;<span class="st"> </span><span class="fl">0.4721949</span> , <span class="dv">1</span>, <span class="dv">0</span>)
<span class="kw">confusionMatrix</span>(<span class="dt">data =</span> prediction_admission_lr, 
                <span class="dt">reference =</span> df$admit, 
                <span class="dt">positive =</span> <span class="st">&quot;1&quot;</span>)</code></pre></div>
<pre><code>## Confusion Matrix and Statistics
## 
##           Reference
## Prediction   0   1
##          0 247  89
##          1  26  38
##                                           
##                Accuracy : 0.7125          
##                  95% CI : (0.6654, 0.7564)
##     No Information Rate : 0.6825          
##     P-Value [Acc &gt; NIR] : 0.1077          
##                                           
##                   Kappa : 0.2352          
##  Mcnemar&#39;s Test P-Value : 7.402e-09       
##                                           
##             Sensitivity : 0.2992          
##             Specificity : 0.9048          
##          Pos Pred Value : 0.5938          
##          Neg Pred Value : 0.7351          
##              Prevalence : 0.3175          
##          Detection Rate : 0.0950          
##    Detection Prevalence : 0.1600          
##       Balanced Accuracy : 0.6020          
##                                           
##        &#39;Positive&#39; Class : 1               
## </code></pre>
<p>And bonus, we even gained some accuracy!</p>
<p>I have seen a very cool graph on <a href="http://ethen8181.github.io/machine-learning/unbalanced/unbalanced.html">this website</a> that plots this tradeoff between specificity and sensitivity and shows how this cutoff point can enhance the understanding of the predictive power of our model.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Create tibble with both prediction and actual value</span>
cutoff =<span class="st"> </span><span class="fl">0.487194</span>
cutoff_plot &lt;-<span class="st"> </span><span class="kw">tibble</span>(<span class="dt">predicted =</span> <span class="kw">predict</span>(model_admission_lr, <span class="dt">data =</span> df, <span class="dt">type =</span> <span class="st">&quot;response&quot;</span>), 
                      <span class="dt">actual =</span> <span class="kw">as.factor</span>(df$admit)) %&gt;%<span class="st"> </span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">type =</span> <span class="kw">if_else</span>(predicted &gt;=<span class="st"> </span>cutoff &amp;<span class="st"> </span>actual ==<span class="st"> </span><span class="dv">1</span>, <span class="st">&quot;TP&quot;</span>, 
                        <span class="kw">if_else</span>(predicted &gt;=<span class="st"> </span>cutoff &amp;<span class="st"> </span>actual ==<span class="st"> </span><span class="dv">0</span>, <span class="st">&quot;FP&quot;</span>, 
                                <span class="kw">if_else</span>(predicted &lt;<span class="st"> </span>cutoff &amp;<span class="st"> </span>actual ==<span class="st"> </span><span class="dv">0</span>, <span class="st">&quot;TN&quot;</span>, <span class="st">&quot;FN&quot;</span>))))

cutoff_plot$type &lt;-<span class="st"> </span><span class="kw">as.factor</span>(cutoff_plot$type)

<span class="kw">ggplot</span>(cutoff_plot, <span class="kw">aes</span>(<span class="dt">x =</span> actual, <span class="dt">y =</span> predicted, <span class="dt">color =</span> type)) +<span class="st"> </span>
<span class="st">  </span><span class="kw">geom_violin</span>(<span class="dt">fill =</span> <span class="st">&quot;white&quot;</span>, <span class="dt">color =</span> <span class="ot">NA</span>) +<span class="st"> </span>
<span class="st">  </span><span class="kw">geom_jitter</span>(<span class="dt">shape =</span> <span class="dv">1</span>) +<span class="st"> </span>
<span class="st">  </span><span class="kw">geom_hline</span>(<span class="dt">yintercept =</span> cutoff, <span class="dt">color =</span> <span class="st">&quot;blue&quot;</span>, <span class="dt">alpha =</span> <span class="fl">0.5</span>) +<span class="st"> </span>
<span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">limits =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">1</span>)) +<span class="st"> </span>
<span class="st">  </span><span class="kw">ggtitle</span>(<span class="kw">paste0</span>(<span class="st">&quot;Confusion Matrix with cutoff at &quot;</span>, cutoff))</code></pre></div>
<p><img src="machinelearningwithR_files/figure-html/confusion_plot1-1.png" width="672" /></p>
<p>Last thing … the AUC, aka <em>Area Under the Curve</em>.<br />
The AUC is basically the area under the ROC curve.<br />
You can think of the AUC as sort of a holistic number that represents how well your TP and FP is looking in aggregate.</p>
<p>AUC=0 -&gt; BAD</p>
<p>AUC=1 -&gt; GOOD <img src="otherpics/AUC_example.png" alt="Area under ROC" /></p>
<p>So in the context of an ROC curve, the more “up and left” it looks, the larger the AUC will be and thus, the better your classifier is. Comparing AUC values is also really useful when comparing different models, as we can select the model with the high AUC value, rather than just look at the curves.</p>
<p>In our situation with our model <code>model_admission_lr</code>, we can find our AUC with the <code>ROCR</code> package.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">prediction_admission_lr &lt;-<span class="st"> </span><span class="kw">predict</span>(model_admission_lr, <span class="dt">data =</span> df, <span class="dt">type=</span><span class="st">&quot;response&quot;</span>)
pr_admission &lt;-<span class="st"> </span><span class="kw">prediction</span>(prediction_admission_lr, df$admit)
auc_admission &lt;-<span class="st"> </span><span class="kw">performance</span>(pr_admission, <span class="dt">measure =</span> <span class="st">&quot;auc&quot;</span>)

<span class="co"># and to get the exact value  </span>
auc_admission@y.values[[<span class="dv">1</span>]]</code></pre></div>
<pre><code>## [1] 0.6928413</code></pre>
</div>
<div id="example-2" class="section level2">
<h2><span class="header-section-number">3.6</span> Example 2</h2>
<p>In our second example we will use the <em>Pima Indians Diabetes Data Set</em> that can be downloaded on the <a href="https://archive.ics.uci.edu/ml/datasets/Pima+Indians+Diabetes">UCI Machine learning website</a>.<br />
We are also dropping a clean version of the file as .csv on our github dataset folder.</p>
<p>The data set records females patients of at least 21 years old of Pima Indian heritage.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">df &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;dataset/diabetes.csv&quot;</span>)</code></pre></div>
<p>The dataset has 768 observations and 9 variables.</p>
<p>Let’s rename our variables with the proper names.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">colnames</span>(df) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;pregnant&quot;</span>, <span class="st">&quot;glucose&quot;</span>, <span class="st">&quot;diastolic&quot;</span>, 
                  <span class="st">&quot;triceps&quot;</span>, <span class="st">&quot;insulin&quot;</span>, <span class="st">&quot;bmi&quot;</span>, <span class="st">&quot;diabetes&quot;</span>, <span class="st">&quot;age&quot;</span>, 
                  <span class="st">&quot;test&quot;</span>)
<span class="kw">glimpse</span>(df)</code></pre></div>
<pre><code>## Observations: 768
## Variables: 9
## $ pregnant  &lt;int&gt; 6, 1, 8, 1, 0, 5, 3, 10, 2, 8, 4, 10, 10, 1, 5, 7, 0...
## $ glucose   &lt;int&gt; 148, 85, 183, 89, 137, 116, 78, 115, 197, 125, 110, ...
## $ diastolic &lt;int&gt; 72, 66, 64, 66, 40, 74, 50, 0, 70, 96, 92, 74, 80, 6...
## $ triceps   &lt;int&gt; 35, 29, 0, 23, 35, 0, 32, 0, 45, 0, 0, 0, 0, 23, 19,...
## $ insulin   &lt;int&gt; 0, 0, 0, 94, 168, 0, 88, 0, 543, 0, 0, 0, 0, 846, 17...
## $ bmi       &lt;dbl&gt; 33.6, 26.6, 23.3, 28.1, 43.1, 25.6, 31.0, 35.3, 30.5...
## $ diabetes  &lt;dbl&gt; 0.627, 0.351, 0.672, 0.167, 2.288, 0.201, 0.248, 0.1...
## $ age       &lt;int&gt; 50, 31, 32, 21, 33, 30, 26, 29, 53, 54, 30, 34, 57, ...
## $ test      &lt;int&gt; 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1...</code></pre>
<p>All variables seems to have been recorded with the appropriate type in the data frame. Let’s just change the type of the response variable to factor with <em>positive</em> and <em>negative</em> levels.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">df$test &lt;-<span class="st"> </span><span class="kw">factor</span>(df$test)
<span class="co">#levels(df$output) &lt;- c(&quot;negative&quot;, &quot;positive&quot;)</span></code></pre></div>
<p>Let’s do our regression on the whole dataset.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">model_diabetes_lr &lt;-<span class="st"> </span><span class="kw">glm</span>(test ~., <span class="dt">data =</span> df, <span class="dt">family =</span> <span class="st">&quot;binomial&quot;</span>)
<span class="kw">summary</span>(model_diabetes_lr)</code></pre></div>
<pre><code>## 
## Call:
## glm(formula = test ~ ., family = &quot;binomial&quot;, data = df)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.5566  -0.7274  -0.4159   0.7267   2.9297  
## 
## Coefficients:
##               Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -8.4046964  0.7166359 -11.728  &lt; 2e-16 ***
## pregnant     0.1231823  0.0320776   3.840 0.000123 ***
## glucose      0.0351637  0.0037087   9.481  &lt; 2e-16 ***
## diastolic   -0.0132955  0.0052336  -2.540 0.011072 *  
## triceps      0.0006190  0.0068994   0.090 0.928515    
## insulin     -0.0011917  0.0009012  -1.322 0.186065    
## bmi          0.0897010  0.0150876   5.945 2.76e-09 ***
## diabetes     0.9451797  0.2991475   3.160 0.001580 ** 
## age          0.0148690  0.0093348   1.593 0.111192    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 993.48  on 767  degrees of freedom
## Residual deviance: 723.45  on 759  degrees of freedom
## AIC: 741.45
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p>If we look at the z-statistic and the associated p-values, we can see that the variables <code>triceps</code>, <code>insulin</code> and <code>age</code> are not significant variables.</p>
<p>The logistic regression coefficients give the change in the log odds of the outcome for a one unit increase in the predictor variable. Hence, everything else being equals, any additional pregnancy increase the log odds of having diabetes (class_variable = 1) by another <code>0.1231</code>.</p>
<p>We can see the confidence interval for each variables using the <code>confint</code> function.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">confint</span>(model_diabetes_lr)</code></pre></div>
<pre><code>## Waiting for profiling to be done...</code></pre>
<pre><code>##                    2.5 %        97.5 %
## (Intercept) -9.860319374 -7.0481062619
## pregnant     0.060918463  0.1868558244
## glucose      0.028092756  0.0426500736
## diastolic   -0.023682464 -0.0031039754
## triceps     -0.012849460  0.0142115759
## insulin     -0.002966884  0.0005821426
## bmi          0.060849478  0.1200608498
## diabetes     0.365370025  1.5386561742
## age         -0.003503266  0.0331865712</code></pre>
<p>If we want to get the odds, we basically exponentiate the coefficients.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">exp</span>(<span class="kw">coef</span>(model_diabetes_lr))</code></pre></div>
<pre><code>##  (Intercept)     pregnant      glucose    diastolic      triceps 
## 0.0002238137 1.1310905981 1.0357892688 0.9867924485 1.0006191560 
##      insulin          bmi     diabetes          age 
## 0.9988090108 1.0938471417 2.5732758592 1.0149800983</code></pre>
<p>In this way, for every additional year of age, the odds of getting diabetes (test = positive) is increasing by <code>1.015</code>.</p>
<p>Let’s have a first look at how our model perform</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">prediction_diabetes_lr &lt;-<span class="st"> </span><span class="kw">predict</span>(model_diabetes_lr, <span class="dt">data =</span> df, <span class="dt">type=</span><span class="st">&quot;response&quot;</span>)
prediction_diabetes_lr &lt;-<span class="st"> </span><span class="kw">if_else</span>(prediction_diabetes_lr &gt;<span class="st"> </span><span class="fl">0.5</span>, <span class="dv">1</span>, <span class="dv">0</span>)
<span class="co">#prediction_diabetes_lr &lt;- factor(prediction_diabetes_lr)</span>
<span class="co">#levels(prediction_diabetes_lr) &lt;- c(&quot;negative&quot;, &quot;positive&quot;)</span>

<span class="kw">table</span>(df$test)</code></pre></div>
<pre><code>## 
##   0   1 
## 500 268</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">confusionMatrix</span>(<span class="dt">data =</span> prediction_diabetes_lr, 
                <span class="dt">reference =</span> df$test, 
                <span class="dt">positive =</span> <span class="st">&quot;1&quot;</span>)</code></pre></div>
<pre><code>## Confusion Matrix and Statistics
## 
##           Reference
## Prediction   0   1
##          0 445 112
##          1  55 156
##                                           
##                Accuracy : 0.7826          
##                  95% CI : (0.7517, 0.8112)
##     No Information Rate : 0.651           
##     P-Value [Acc &gt; NIR] : 1.373e-15       
##                                           
##                   Kappa : 0.4966          
##  Mcnemar&#39;s Test P-Value : 1.468e-05       
##                                           
##             Sensitivity : 0.5821          
##             Specificity : 0.8900          
##          Pos Pred Value : 0.7393          
##          Neg Pred Value : 0.7989          
##              Prevalence : 0.3490          
##          Detection Rate : 0.2031          
##    Detection Prevalence : 0.2747          
##       Balanced Accuracy : 0.7360          
##                                           
##        &#39;Positive&#39; Class : 1               
## </code></pre>
<p>Let’s create our ROC curve</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">prediction_diabetes_lr &lt;-<span class="st"> </span><span class="kw">predict</span>(model_diabetes_lr, <span class="dt">data =</span> df, <span class="dt">type=</span><span class="st">&quot;response&quot;</span>)
pr_diabetes &lt;-<span class="st"> </span><span class="kw">prediction</span>(prediction_diabetes_lr, df$test)
prf_diabetes &lt;-<span class="st"> </span><span class="kw">performance</span>(pr_diabetes, <span class="dt">measure =</span> <span class="st">&quot;tpr&quot;</span>, <span class="dt">x.measure =</span> <span class="st">&quot;fpr&quot;</span>)
<span class="kw">plot</span>(prf_diabetes, <span class="dt">colorize =</span> <span class="ot">TRUE</span>, <span class="dt">lwd =</span> <span class="dv">3</span>)</code></pre></div>
<p><img src="machinelearningwithR_files/figure-html/roc_diabetes_pic1-1.png" width="672" /></p>
<p>Let’s find the best cutoff value for our model.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">cost_diabetes_perf =<span class="st"> </span><span class="kw">performance</span>(pr_diabetes, <span class="st">&quot;cost&quot;</span>)
pr_diabetes@cutoffs[[<span class="dv">1</span>]][<span class="kw">which.min</span>(cost_diabetes_perf@y.values[[<span class="dv">1</span>]])]</code></pre></div>
<pre><code>##      294 
## 0.486768</code></pre>
<p>Instead of redoing the whole violin-jitter graph for our model, let’s create a function so we can reuse it at a later stage.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">violin_jitter_graph &lt;-<span class="st"> </span>function(cutoff, df_predicted, df_actual){
  cutoff_tibble &lt;-<span class="st"> </span><span class="kw">tibble</span>(<span class="dt">predicted =</span> df_predicted, <span class="dt">actual =</span> <span class="kw">as.factor</span>(df_actual)) %&gt;%<span class="st"> </span>
<span class="st">                 </span><span class="kw">mutate</span>(<span class="dt">type =</span> <span class="kw">if_else</span>(predicted &gt;=<span class="st"> </span>cutoff &amp;<span class="st"> </span>actual ==<span class="st"> </span><span class="dv">1</span>, <span class="st">&quot;TP&quot;</span>, 
                                       <span class="kw">if_else</span>(predicted &gt;=<span class="st"> </span>cutoff &amp;<span class="st"> </span>actual ==<span class="st"> </span><span class="dv">0</span>, <span class="st">&quot;FP&quot;</span>, 
                                               <span class="kw">if_else</span>(predicted &lt;<span class="st"> </span>cutoff &amp;<span class="st"> </span>actual ==<span class="st"> </span><span class="dv">0</span>, <span class="st">&quot;TN&quot;</span>, <span class="st">&quot;FN&quot;</span>))))
  cutoff_tibble$type &lt;-<span class="st"> </span><span class="kw">as.factor</span>(cutoff_tibble$type)
  
  <span class="kw">ggplot</span>(cutoff_tibble, <span class="kw">aes</span>(<span class="dt">x =</span> actual, <span class="dt">y =</span> predicted, <span class="dt">color =</span> type)) +<span class="st"> </span>
<span class="st">    </span><span class="kw">geom_violin</span>(<span class="dt">fill =</span> <span class="st">&quot;white&quot;</span>, <span class="dt">color =</span> <span class="ot">NA</span>) +<span class="st"> </span>
<span class="st">    </span><span class="kw">geom_jitter</span>(<span class="dt">shape =</span> <span class="dv">1</span>) +<span class="st"> </span>
<span class="st">    </span><span class="kw">geom_hline</span>(<span class="dt">yintercept =</span> cutoff, <span class="dt">color =</span> <span class="st">&quot;blue&quot;</span>, <span class="dt">alpha =</span> <span class="fl">0.5</span>) +<span class="st"> </span>
<span class="st">    </span><span class="kw">scale_y_continuous</span>(<span class="dt">limits =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">1</span>)) +<span class="st"> </span>
<span class="st">    </span><span class="kw">ggtitle</span>(<span class="kw">paste0</span>(<span class="st">&quot;Confusion Matrix with cutoff at &quot;</span>, cutoff))
}


<span class="kw">violin_jitter_graph</span>(<span class="fl">0.486768</span>, <span class="kw">predict</span>(model_diabetes_lr, <span class="dt">data =</span> df, <span class="dt">type =</span> <span class="st">&quot;response&quot;</span>), df$test)</code></pre></div>
<p><img src="machinelearningwithR_files/figure-html/confusion_plot2-1.png" width="672" /></p>
<p>The accuracy of our model is slightly improved by using that new cutoff value.</p>
<div id="accounting-for-missing-values" class="section level3">
<h3><span class="header-section-number">3.6.1</span> Accounting for missing values</h3>
<p>The UCI Machine Learning website note that there are no missing values on this dataset. That said, we have to be careful as there are many 0, when it is actually impossible to have such 0.<br />
So before we keep going let’s fill in these values.</p>
<p>The first thing to to is to change these <code>0</code> into <code>NA</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">df2 &lt;-<span class="st"> </span>df

<span class="co">#TODO Find a way to create a function and use map from purrr to do this</span>
df2$glucose[df2$glucose ==<span class="st"> </span><span class="dv">0</span>] &lt;-<span class="st"> </span><span class="ot">NA</span>
df2$diastolic[df2$diastolic ==<span class="st"> </span><span class="dv">0</span>] &lt;-<span class="st"> </span><span class="ot">NA</span>
df2$triceps[df2$triceps ==<span class="st"> </span><span class="dv">0</span>] &lt;-<span class="st"> </span><span class="ot">NA</span>
df2$insulin[df2$insulin ==<span class="st"> </span><span class="dv">0</span>] &lt;-<span class="st"> </span><span class="ot">NA</span>
df2$bmi[df2$bmi ==<span class="st"> </span><span class="dv">0</span>] &lt;-<span class="st"> </span><span class="ot">NA</span></code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(visdat)
<span class="kw">vis_dat</span>(df2)</code></pre></div>
<p><img src="machinelearningwithR_files/figure-html/missingdata_pic1-1.png" width="672" /></p>
<p>There are a lot of missing values … too many of them really. If this was really life, it would be important to go back to the drawing board and redisigning the data collection phase.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">model_diabetes_lr2 &lt;-<span class="st"> </span><span class="kw">glm</span>(test ~., <span class="dt">data =</span> df2, <span class="dt">family =</span> <span class="st">&quot;binomial&quot;</span>)
<span class="kw">summary</span>(model_diabetes_lr2)</code></pre></div>
<pre><code>## 
## Call:
## glm(formula = test ~ ., family = &quot;binomial&quot;, data = df2)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.7823  -0.6603  -0.3642   0.6409   2.5612  
## 
## Coefficients:
##               Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -1.004e+01  1.218e+00  -8.246  &lt; 2e-16 ***
## pregnant     8.216e-02  5.543e-02   1.482  0.13825    
## glucose      3.827e-02  5.768e-03   6.635 3.24e-11 ***
## diastolic   -1.420e-03  1.183e-02  -0.120  0.90446    
## triceps      1.122e-02  1.708e-02   0.657  0.51128    
## insulin     -8.253e-04  1.306e-03  -0.632  0.52757    
## bmi          7.054e-02  2.734e-02   2.580  0.00989 ** 
## diabetes     1.141e+00  4.274e-01   2.669  0.00760 ** 
## age          3.395e-02  1.838e-02   1.847  0.06474 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 498.10  on 391  degrees of freedom
## Residual deviance: 344.02  on 383  degrees of freedom
##   (376 observations deleted due to missingness)
## AIC: 362.02
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p>This leads to a very different results than previously.</p>
<p>Let’s have a look at this new model performance</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">prediction_diabetes_lr2 &lt;-<span class="st"> </span><span class="kw">predict</span>(model_diabetes_lr2, <span class="dt">data =</span> df2, <span class="dt">type=</span><span class="st">&quot;response&quot;</span>)
prediction_diabetes_lr2 &lt;-<span class="st"> </span><span class="kw">if_else</span>(prediction_diabetes_lr2 &gt;<span class="st"> </span><span class="fl">0.5</span>, <span class="dv">1</span>, <span class="dv">0</span>)
<span class="co">#prediction_diabetes_lr &lt;- factor(prediction_diabetes_lr)</span>
<span class="co">#levels(prediction_diabetes_lr) &lt;- c(&quot;negative&quot;, &quot;positive&quot;)</span>

<span class="kw">table</span>(df2$test)</code></pre></div>
<pre><code>## 
##   0   1 
## 500 268</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#confusionMatrix(data = prediction_diabetes_lr2, </span>
<span class="co">#                reference = df2$test, </span>
<span class="co">#                positive = &quot;1&quot;)</span></code></pre></div>
</div>
<div id="imputting-missing-values" class="section level3">
<h3><span class="header-section-number">3.6.2</span> Imputting Missing Values</h3>
<p>Now let’s impute the missing values using the <code>simputatiion</code> package. A nice vignette is available <a href="https://cran.r-project.org/web/packages/simputation/vignettes/intro.html">here</a>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(simputation)
df3 &lt;-<span class="st"> </span><span class="kw">impute_lm</span>(df2, <span class="dt">formula =</span> glucose ~<span class="st"> </span>pregnant +<span class="st"> </span>diabetes +<span class="st"> </span>age |<span class="st"> </span>test)
df3 &lt;-<span class="st"> </span><span class="kw">impute_rf</span>(df3, <span class="dt">formula =</span> bmi ~<span class="st"> </span>glucose +<span class="st"> </span>pregnant +<span class="st"> </span>diabetes +<span class="st"> </span>age |<span class="st"> </span>test)
df3 &lt;-<span class="st"> </span><span class="kw">impute_rf</span>(df3, <span class="dt">formula =</span> diastolic ~<span class="st"> </span>bmi +<span class="st"> </span>glucose +<span class="st"> </span>pregnant +<span class="st"> </span>diabetes +<span class="st"> </span>age |<span class="st"> </span>test)
df3 &lt;-<span class="st"> </span><span class="kw">impute_en</span>(df3, <span class="dt">formula =</span> triceps ~<span class="st"> </span>pregnant +<span class="st"> </span>bmi +<span class="st"> </span>diabetes +<span class="st"> </span>age |<span class="st"> </span>test)
df3 &lt;-<span class="st"> </span><span class="kw">impute_rf</span>(df3, <span class="dt">formula =</span> insulin ~<span class="st"> </span>. |<span class="st"> </span>test)

<span class="kw">summary</span>(df3)</code></pre></div>
<pre><code>##     pregnant         glucose         diastolic         triceps     
##  Min.   : 0.000   Min.   : 44.00   Min.   : 24.00   Min.   : 7.00  
##  1st Qu.: 1.000   1st Qu.: 99.75   1st Qu.: 64.00   1st Qu.:22.00  
##  Median : 3.000   Median :117.00   Median : 72.00   Median :28.98  
##  Mean   : 3.845   Mean   :121.68   Mean   : 72.37   Mean   :28.90  
##  3rd Qu.: 6.000   3rd Qu.:141.00   3rd Qu.: 80.00   3rd Qu.:35.00  
##  Max.   :17.000   Max.   :199.00   Max.   :122.00   Max.   :99.00  
##     insulin           bmi           diabetes           age        test   
##  Min.   : 14.0   Min.   :18.20   Min.   :0.0780   Min.   :21.00   0:500  
##  1st Qu.: 94.0   1st Qu.:27.50   1st Qu.:0.2437   1st Qu.:24.00   1:268  
##  Median :136.4   Median :32.15   Median :0.3725   Median :29.00          
##  Mean   :155.8   Mean   :32.43   Mean   :0.4719   Mean   :33.24          
##  3rd Qu.:191.1   3rd Qu.:36.60   3rd Qu.:0.6262   3rd Qu.:41.00          
##  Max.   :846.0   Max.   :67.10   Max.   :2.4200   Max.   :81.00</code></pre>
<p>Ok we managed to get rid of the NAs. Let’s run a last time our logistic model.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">model_diabetes_lr3 &lt;-<span class="st"> </span><span class="kw">glm</span>(test ~<span class="st"> </span>., <span class="dt">data =</span> df3, <span class="dt">family =</span> <span class="st">&quot;binomial&quot;</span>)
<span class="kw">summary</span>(model_diabetes_lr3)</code></pre></div>
<pre><code>## 
## Call:
## glm(formula = test ~ ., family = &quot;binomial&quot;, data = df3)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -3.2736  -0.7058  -0.3885   0.7160   2.3767  
## 
## Coefficients:
##              Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -8.661989   0.822515 -10.531  &lt; 2e-16 ***
## pregnant     0.127335   0.032259   3.947 7.90e-05 ***
## glucose      0.031167   0.004146   7.518 5.57e-14 ***
## diastolic   -0.006870   0.008683  -0.791  0.42882    
## triceps      0.004414   0.014432   0.306  0.75973    
## insulin      0.003243   0.001335   2.429  0.01515 *  
## bmi          0.082047   0.020819   3.941 8.11e-05 ***
## diabetes     0.837710   0.297903   2.812  0.00492 ** 
## age          0.009674   0.009712   0.996  0.31918    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 993.48  on 767  degrees of freedom
## Residual deviance: 705.44  on 759  degrees of freedom
## AIC: 723.44
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">accuracy_model_lr3 &lt;-<span class="st"> </span><span class="kw">predict</span>(model_diabetes_lr3, <span class="dt">data =</span> df3, <span class="dt">type=</span><span class="st">&quot;response&quot;</span>)
accuracy_model_lr3 &lt;-<span class="st"> </span><span class="kw">if_else</span>(accuracy_model_lr3 &gt;<span class="st"> </span><span class="fl">0.5</span>, <span class="st">&quot;positive&quot;</span>, <span class="st">&quot;negative&quot;</span>)
accuracy_model_lr3 &lt;-<span class="st"> </span><span class="kw">factor</span>(accuracy_model_lr3)
<span class="kw">levels</span>(accuracy_model_lr3) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;negative&quot;</span>, <span class="st">&quot;positive&quot;</span>)



<span class="kw">table</span>(df3$test, accuracy_model_lr3)</code></pre></div>
<pre><code>##    accuracy_model_lr3
##     negative positive
##   0      442       58
##   1      112      156</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">table</span>(df3$test)</code></pre></div>
<pre><code>## 
##   0   1 
## 500 268</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">########

<span class="co">#confusionMatrix(data = accuracy_model_lr3, </span>
<span class="co">#                reference = df3$test, </span>
<span class="co">#                positive = &quot;positive&quot;)</span></code></pre></div>
</div>
<div id="roc-and-auc" class="section level3">
<h3><span class="header-section-number">3.6.3</span> ROC and AUC</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">accuracy_model_lr3 &lt;-<span class="st"> </span><span class="kw">predict</span>(model_diabetes_lr3, <span class="dt">data =</span> df3, <span class="dt">type=</span><span class="st">&quot;response&quot;</span>)
pr &lt;-<span class="st"> </span><span class="kw">prediction</span>(accuracy_model_lr3, df3$test)
prf &lt;-<span class="st"> </span><span class="kw">performance</span>(pr, <span class="dt">measure =</span> <span class="st">&quot;tpr&quot;</span>, <span class="dt">x.measure =</span> <span class="st">&quot;fpr&quot;</span>)
<span class="kw">plot</span>(prf)</code></pre></div>
<p><img src="machinelearningwithR_files/figure-html/roc_model3_pic1-1.png" width="672" /></p>
<p>Let’s go back to the ideal cut off point that would balance the sensitivity and specificity.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">cost_diabetes_perf &lt;-<span class="st"> </span><span class="kw">performance</span>(pr, <span class="st">&quot;cost&quot;</span>)
pr@cutoffs[[<span class="dv">1</span>]][<span class="kw">which.min</span>(cost_diabetes_perf@y.values[[<span class="dv">1</span>]])]</code></pre></div>
<pre><code>##        10 
## 0.4532151</code></pre>
<p>So for maximum accuracy, the ideal cutoff point is <code>0.487194</code>.<br />
Let’s redo our confusion matrix then and see some improvement.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">accuracy_model_lr3 &lt;-<span class="st"> </span><span class="kw">predict</span>(model_diabetes_lr3, <span class="dt">data =</span> df3, <span class="dt">type=</span><span class="st">&quot;response&quot;</span>)
accuracy_model_lr3 &lt;-<span class="st"> </span><span class="kw">if_else</span>(accuracy_model_lr3 &gt;=<span class="st"> </span><span class="fl">0.487194</span>, <span class="st">&quot;positive&quot;</span>, <span class="st">&quot;negative&quot;</span>)

<span class="co">#confusionMatrix(data = accuracy_model_lr3, </span>
<span class="co">#                reference = df3$test, </span>
<span class="co">#                positive = &quot;positive&quot;)</span></code></pre></div>
<p>Another cost measure that is popular is overall accuracy. This measure optimizes the correct results, but may be skewed if there are many more negatives than positives, or vice versa. Let’s get the overall accuracy for the simple predictions and plot it.</p>
<p>Actually the <code>ROCR</code> package can also give us a plot of accuracy for various cutoff points</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">accuracy_diabetes_lr3 &lt;-<span class="st"> </span><span class="kw">performance</span>(pr, <span class="dt">measure =</span> <span class="st">&quot;acc&quot;</span>)
<span class="kw">plot</span>(accuracy_diabetes_lr3)</code></pre></div>
<p><img src="machinelearningwithR_files/figure-html/roc_model3_pic2-1.png" width="672" /></p>
<p>Often in medical research for instance, there is a cost in having false negative is quite higher than a false positve.<br />
Let’s say the cost of missing someone having diabetes is 3 times the cost of telling someone that he has diabetes when in reality he/she doesn’t.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">cost_diabetes_perf &lt;-<span class="st"> </span><span class="kw">performance</span>(pr, <span class="st">&quot;cost&quot;</span>, <span class="dt">cost.fp =</span> <span class="dv">1</span>, <span class="dt">cost.fn =</span> <span class="dv">3</span>)
pr@cutoffs[[<span class="dv">1</span>]][<span class="kw">which.min</span>(cost_diabetes_perf@y.values[[<span class="dv">1</span>]])]</code></pre></div>
<pre><code>##       420 
## 0.1711154</code></pre>
<p>Lastly, in regards to AUC</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">auc &lt;-<span class="st"> </span><span class="kw">performance</span>(pr, <span class="dt">measure =</span> <span class="st">&quot;auc&quot;</span>)
auc &lt;-<span class="st"> </span>auc@y.values[[<span class="dv">1</span>]]
auc</code></pre></div>
<pre><code>## [1] 0.8528358</code></pre>
</div>
</div>
<div id="references" class="section level2">
<h2><span class="header-section-number">3.7</span> References</h2>
<ul>
<li><p>The Introduction is from the <a href="https://www.analyticsvidhya.com/blog/2015/11/beginners-guide-on-logistic-regression-in-r/?utm_content=buffer43450&amp;utm_medium=social&amp;utm_source=linkedin.com&amp;utm_campaign=buffer">AV website</a></p></li>
<li><p>Confusion plot. The <a href="http://ethen8181.github.io/machine-learning/unbalanced/unbalanced.html">webpage</a> and the <a href="https://github.com/ethen8181/machine-learning/blob/master/unbalanced/unbalanced_code/unbalanced_functions.R">code</a></p></li>
<li><p>The <a href="http://www.ats.ucla.edu/stat/data/binary.csv">UCLA Institute for Digital Research and Education</a> site where we got the dataset for our first example</p></li>
<li>The <a href="https://archive.ics.uci.edu/ml/datasets/Pima+Indians+Diabetes">UCI Machine learning</a> site where we got the dataset for our second example</li>
<li><p>Function to use ROC with ggplot2 - <a href="http://www.joyofdata.de/blog/illustrated-guide-to-roc-and-auc/">The Joy of Data</a> and <a href="https://github.com/joyofdata/joyofdata-articles/tree/master/roc-auc">here as well</a></p></li>
</ul>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="intro.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="trees-and-classification.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/fderyckel/bookdown-demo/edit/master/03-logistic_regression.Rmd",
"text": "Edit"
},
"download": ["machinelearningwithR.pdf"],
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    if (location.protocol !== "file:" && /^https?:/.test(script.src))
      script.src  = script.src.replace(/^https?:/, '');
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
